"""Verification wrapper exit-code and dependency-lock policy tests."""

from __future__ import annotations


def test_makefile_lint_does_not_hide_mypy_failures(repo_root):
    text = (repo_root / "Makefile").read_text(encoding="utf-8")
    lint = text.split("lint:", 1)[1].split("\n\n", 1)[0]
    assert "mypy" in lint
    assert "|| true" not in lint


def test_makefile_security_does_not_mask_tool_failures(repo_root):
    text = (repo_root / "Makefile").read_text(encoding="utf-8")
    security = text.split("security:", 1)[1].split("\n\n", 1)[0]
    assert "verify-security" in security
    assert "bandit" in security
    assert "verify-deps" in security
    assert "||" not in security


def test_local_pipeline_treats_bandit_as_blocking(repo_root):
    text = (repo_root / "scripts" / "verify_pipeline.sh").read_text(encoding="utf-8")
    assert "static_analysis.py bandit --mode blocking" in text
    assert 'static_analysis.py "$tool" --mode report-only' in text


def test_generated_requirements_are_derived_from_uv_lock(repo_root):
    requirements = (repo_root / "requirements.txt").read_text(encoding="utf-8")
    assert (repo_root / "uv.lock").is_file()
    assert "autogenerated by uv" in requirements
    assert "uv export --frozen --no-emit-project" in requirements
